### ISSUE TITLE
Unable to train on many agents

### ISSUE THREAD

**Issue by hmomin** [AI4Finance-Foundation/ElegantRL#118]
Whenever I try to train on agents, I consistently get the error:

```
AttributeError: type object 'AgentXYZ' has no attribute 'if_off_policy'
```

For example, here is the error for `AgentDQN`:

```
Traceback (most recent call last):
  File "/home/momin/Documents/GitHub/ElegantRL/tests/test_training_agents.py", line 50, in test_should_create_arguments_for_each_agent
    Arguments(agent, env_func=gym.make, env_args=self.discrete_env_args)
  File "/home/momin/Documents/GitHub/ElegantRL/elegantrl/train/config.py", line 140, in __init__
    self.if_off_policy = agent.if_off_policy  # agent is on-policy or off-policy
AttributeError: type object 'AgentDQN' has no attribute 'if_off_policy'
```

I can confirm that this error affects the following agents:
`AgentDQN`
`AgentD3QN`
`AgentDDPG`
`AgentDiscretePPO`
`AgentDoubleDQN`
`AgentDuelingDQN`
`AgentModSAC`
`AgentPPO_H`
`AgentPPO`
`AgentSAC_H`
`AgentSAC`
`AgentTD3`

@shixun404

**Comment by hmomin** [comment]
Shixun, if you'd like me to help out with this, I'm happy to. However, since I've noticed you're working very closely with the agents files, I'd prefer you handle this to avoid any merge conflicts between us. I'm mostly fixing some issues that have popped up related to Isaac Gym.

**Comment by shixun404** [comment]
Sure, no problem at all. I will handle it this evening.

**Comment by richardhuo** [comment]
Same issue happened to me since yesterday tried to run FinRL via colab: Compare ElegantRL, RLlib, and Stablebaselines3. 
the elegantrl package was no longer available from that time. 
I managed to install the package from local but in the end received the same issue of : type object 'AgentXXX' has no attribute 'if_off_policy'

**Comment by yizhangliu** [comment]
ImportError: cannot import name 'SharePPO' from 'elegantrl.agents.net'

**Comment by hmomin** [comment]
@richardhuo - that issue should be fixed by now, but you may be running into a different issue where agents cannot be imported from `elegantrl.agent`. I'll address it tomorrow...

@yizhangliu - that bug should be fixed now.

The original bug should also be fixed now in commit 5d95ce9.

**Comment by farzinaghdam** [comment]
I am still experiencing this problem. It works fine on Colab. However on my local machine I get 
  File FinRL-Meta/agents/elegantrl_models.py", line 59, in get_model
    model = Arguments(agent=agent, env=env)
  File "python3.8/site-packages/elegantrl/train/config.py", line 127, in __init__
    self.if_off_policy = agent.if_off_policy  # agent is on-policy or off-policy
AttributeError: module 'elegantrl.agents.AgentPPO' has no attribute 'if_off_policy'

Thanks

**Comment by hmomin** [comment]
@farzinaghdam
I suggest you try reinstalling ElegantRL on your local machine. I've just pulled the latest commit and all the relevant PPO tests are passing on my machine.

**Comment by farzinaghdam** [comment]
Thank you for quick reply.
 I downgraded gym to 0.17.3 (which is the one used on my Colab at the moment) and reinstalled various packages and it works fine now. Thank you.
